#!/usr/bin/env bash
#
# Generate the Pulp server RSA key pair.

#####
# Shamelessly stolen and modified from Pulp master branch (2.13). This normally
# gets installed in /usr/bin/
#####

set -e

KEY_DIR="certs"
KEY_PATH="$KEY_DIR/rsa.key"
KEY_PATH_PUB="$KEY_DIR/rsa_pub.key"

umask 077

openssl genrsa -out ${KEY_PATH} 2048 &> /dev/null
openssl rsa -in ${KEY_PATH} -pubout > ${KEY_PATH_PUB} 2> /dev/null

chmod 640 ${KEY_PATH}
chmod 644 ${KEY_PATH_PUB}

echo "Created: ${KEY_PATH} and ${KEY_PATH_PUB}"
